version: "3.9"

services:
  web:
    image: nginx:alpine
    environment:
      - VIRTUAL_HOST=josefbouse.cz
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=josefbouse.cz
      - LETSENCRYPT_EMAIL=info@josefbouse.cz
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
